general_translation:
  prompt_path: /Volumes/nafiska/empathy_dataset_transfer/configs/prompts/translation_prompt.txt
  model_config_path: /Volumes/nafiska/empathy_dataset_transfer/configs/conf.json
  filepath_examples: /Volumes/nafiska/empathy_dataset_transfer/configs/filepath_examples.json
  batch_size: 4
  batch_result_dir: batches_res_general_translation
  batches: batches_general_translation
  data_path: /Volumes/nafiska/empathy_dataset_transfer/data/emr.csv
  cols: id text

general_translation_correction:
  prompt_path: /Volumes/nafiska/empathy_dataset_transfer/configs/prompts/translation_correction_prompt.txt
  model_config_path: /Volumes/nafiska/empathy_dataset_transfer/configs/conf.json
  filepath_examples: /Volumes/nafiska/empathy_dataset_transfer/configs/filepath_examples_cor.json
  batch_size: 4
  batch_result_dir: batches_res_general_translation_correcton
  batches: batches_general_translation_correction

rationales_translation:
  prompt_path: /Volumes/nafiska/empathy_dataset_transfer/configs/prompts/rationales_translation_prompt.txt
  model_config_path: /Volumes/nafiska/empathy_dataset_transfer/configs/conf.json
  filepath_examples: /Volumes/nafiska/empathy_dataset_transfer/configs/filepath_examples_rat.json
  batch_size: 4
  batch_result_dir: batches_res_rationales_translation
  batches: batches_rationales_translation
  data_path: /Volumes/nafiska/empathy_dataset_transfer/data/rats.json
  cols: id text_rus text_eng rationales_eng 

rationales_translation_correction:
  prompt_path: /Volumes/nafiska/empathy_dataset_transfer/configs/prompts/rationales_translation_correction_prompt.txt
  model_config_path: /Volumes/nafiska/empathy_dataset_transfer/configs/conf.json
  filepath_examples: /Volumes/nafiska/empathy_dataset_transfer/configs/filepath_examples_cor_rat.json
  batch_size: 4
  batch_result_dir: batches_res_rationales_translation_correction
  batches: batches_rationales_translation_correction