[DEFAULT]
prompt_path = /Volumes/nafiska/empathy_dataset_transfer/configs/prompts/rationales_translation_correction_prompt.txt
model_config_path = /Volumes/nafiska/empathy_dataset_transfer/configs/conf.json
filepath_examples = /Volumes/nafiska/empathy_dataset_transfer/configs/filepath_examples_cor_rat.json
batch_size = 4
batch_result_dir = batches_res
batches = batches
